services:
  redis:
    image: redis:alpine
    # container_name: redis
    ports:
      - "6379:6379"
    networks:
      - django_network

  db:
    image: postgres:13
    # container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - django_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    # container_name: django_app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - django_network

  celery_worker:
    build:
      context: .
      dockerfile: ./celery_worker/Dockerfile
    # container_name: celery_worker
    command: celery -A price_scraper worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db
    networks:
      - django_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  celery_beat:
    build:
      context: .
      dockerfile: ./celery_beat/Dockerfile
    command: celery -A price_scraper beat --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - db
    networks:
      - django_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:

networks:
  django_network:
